### ISSUE TITLE
Publications citing OpenIFEM

### ISSUE THREAD

**Issue by bangerth** [OpenIFEM/OpenIFEM#13]
Since OpenIFEM builds on deal.II, I'd like to ask for a favor:

We like to keep a list of all publications building on deal.II at https://www.dealii.org/publications.html . I've just added the paper by Cheng et al., 2019 to that list. Do any of the other papers you list in the README.md at https://github.com/OpenIFEM/OpenIFEM use deal.II?

But more interesting to me would be if you had a list of publications that build on OpenIFEM? These then transitively also build on deal.II, and I'd be interested in listing them on our website -- it's just good advertising for everyone :-)

Thanks in advance! -- Wolfgang

**Comment by yufeimi** [comment]
Hi Wolfgang,

Thanks for your interest. The 2019 paper in README.md is the only one that uses deal.II, as we started re-implementing everything that was originally in Fortran in 2017.
Currently we do not have publications that build on OpenIFEM, but we are working on a paper (with OpenIFEM) and will update on dealii user group once we publish it.
Will also update when we have any new publication in the future.

Thanks!
Feimi

**Comment by bangerth** [comment]
Excellent, @yufeimi! We look forward to any papers you have that build on deal.II. The easiest is if you either follow the description at https://github.com/dealii/publication-list or, even simpler for you, if you just open a github issue at that link page that contains the bibtex entry.

Thanks in advance!

**Comment by lucy-t-zhang** [comment]
Thank you, Wolfgang, for reaching out to us. Our IFEM code is now entirely based on deal.II and we’ll be contributing greatly in fluid-structure interaction algorithm developments. 
We will continuously update the reference list. 
Best Regards, 


Lucy Zhang
Associate Professor
Department of Mechanical, Aerospace & Nuclear Engineering
Rensselaer Polytechnic Institute
