### ISSUE TITLE
global refinement for RKPM limit

### ISSUE THREAD

**Issue by shenchen-rpi** [OpenIFEM/OpenIFEM#17]
RKPM solver will lead to segmentation fault when it has too many cells and dofs

To reproduce the issue:
1. Go to /tests/rkpm-rk4-bending-mpi/
2. Set global refinement for solid to 2
3. Run rkpm-rk4-bending-mpi test case

**Comment by yufeimi** [comment]
This is due to the unchanged support size of the RKPM solver which results in neighbor size exceeding the maximally allowed number. One should keep the support size the same as the mesh size.
