### ISSUE TITLE
It seems the codes  are incomplete!

### ISSUE THREAD

**Issue by buaayhq** [OpenIFEM/OpenIFEM#24]
Comparing the codes with papers[OpenIFEM: A High Performance Modular Open-Source Software of the Immersed Finite Element Method for Fluid-Structure Interactions&&Modified immersed finite element method for fully-coupled fluid–structure interactions], some formulars are different.
Currently, can OpenIFEM reproduce the results in the papers?
Thank you!

**Comment by yufeimi** [comment]
Hi,

The code is evolving due to our research needs and we are not sticking to a fixed formulation. Would you mind reminding me which case you would like to reproduce?

Thanks,
Feimi

**Comment by buaayhq** [comment]
Dear feimi, 
thank you for your response.
One of the major confusions is the variable `fsi_stress=0` throughout the code. However, for example, in insim.cpp line 277 
```c
                if (ind == 1)
                  {
                    local_rhs(i) +=
                      (scalar_product(grad_phi_u[i], p[0]->fsi_stress) +
                       p[0]->fsi_acceleration * phi_u[i]) *
                      fe_values.JxW(q);
                  }
```
In other words, when computing the fsi force, there is no contribution of the stress, which is different from the formular in the papers.
