### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by MWAG91** [OpenIFEM/OpenIFEM#48]
[OpenIFEM_log.txt](https://github.com/OpenIFEM/OpenIFEM/files/11489915/OpenIFEM_log.txt)
[dealii_test_log.txt](https://github.com/OpenIFEM/OpenIFEM/files/11489916/dealii_test_log.txt)

I am trying to install OpenIFEM on Ubuntu, but, during the installation I get an error at 
"[ 20%] Building CXX object source/CMakeFiles/openifem.dir/mpi_shared_solid_solver.cpp.o" 
and the installation is then aborted. Beforehand, I have managed to install deal.II with all the required dependencies, however, I wonder if the problem might have something to do with the fact I have installed the latest versions of the dependencies and OpenIFEM might be only compatible with older versions. I say this because at an earlier stage of the installation at 
"[ 15%] Building CXX object source/CMakeFiles/openifem.dir/mpi_insim_supg.cpp.o"
I get this
"warning: ‘using PreconditionerBase = class dealii::PETScWrappers::PreconditionBase’ is deprecated [-Wdeprecated-declarations]". 
If that is the issue, then could you let me know of the versions of the dependencies that you run OpenIFEM with so I can reinstall them. My dependencies versions are:
1- MPICH: MPI_VERSION = 4.0
2- PETSc: 3.19.1.
3- p4est: 2.8.5.5-9ddbb
4- METIS: 5.1.0
5- deal.II: 9.4.1

I have attached the file "OpenIFEM_log" wherein I have included the complete terminal log of downloading, building, and installing OpenIFEM. My deal.II works fine with all the dependencies as shown in the attached deal.II tests log "dealii_test_log.txt" that confirms that. I would genuinely appreciate any help or guidance to fix the issue as I am not an expert.

**Comment by yufeimi** [comment]
The log suggests that deal.ii's API for data output has changed in 9.4. Can you trying installing OpenIFEM with dealii. 9.3? The last adaptation I did was for 9.3.

**Comment by shenchen0414** [comment]
Dealii 9.3.1. works, i need to testing 9.4 and fix the incompatibility

**Comment by MWAG91** [comment]
Many thanks for your prompt responses.

I have installed deal.II 9.3.1 (which went smoothly as verified in the test shown in the attached "dealii_test_log.txt" ), while keeping all other dependencies without change. I have then tried to install OpenIFEM again and this time it progressed further than the first time but when it reached:
[ 29%] Building CXX object source/CMakeFiles/openifem.dir/utilities.cpp.o
it then aborted due to fatal errors as shown in the attached "OpenIFEM_log" . There seems to be a lot of petsc mentions in this error, and so I wonder again if this time it has to do with dependencies versions and I need to downgrade petsc? if that is the case, would you please let me know of the dependencies versions you are running OpenIFEM on so I can replicate them, namely:
1- MPI:
2- PETSc: , Mumps: , Hypre:
3- p4est:
4- METIS:
5- deal.II: 9.3.1
Blas:
Lapack:
Scalapack
Umfpack:

I really appreciate your help.

[dealii_test_log.txt](https://github.com/OpenIFEM/OpenIFEM/files/11501824/dealii_test_log.txt)
[OpenIFEM_log.txt](https://github.com/OpenIFEM/OpenIFEM/files/11501825/OpenIFEM_log.txt)

**Comment by shenchen0414** [comment]
Your petsc version is 3.19.1. Based on dealii's documentation on interfacing with petsc, the latest stable version is 3.17.1. Can you please try to use an earlier version of petsc?
See this link: [https://www.dealii.org/current/external-libs/petsc.html](url)

**Comment by shenchen0414** [comment]
> Many thanks for your prompt responses.
> 
> I have installed deal.II 9.3.1 (which went smoothly as verified in the test shown in the attached "dealii_test_log.txt" ), while keeping all other dependencies without change. I have then tried to install OpenIFEM again and this time it progressed further than the first time but when it reached: [ 29%] Building CXX object source/CMakeFiles/openifem.dir/utilities.cpp.o it then aborted due to fatal errors as shown in the attached "OpenIFEM_log" . There seems to be a lot of petsc mentions in this error, and so I wonder again if this time it has to do with dependencies versions and I need to downgrade petsc? if that is the case, would you please let me know of the dependencies versions you are running OpenIFEM on so I can replicate them, namely: 1- MPI: 2- PETSc: , Mumps: , Hypre: 3- p4est: 4- METIS: 5- deal.II: 9.3.1 Blas: Lapack: Scalapack Umfpack:
> 
> I really appreciate your help.
> 
> [dealii_test_log.txt](https://github.com/OpenIFEM/OpenIFEM/files/11501824/dealii_test_log.txt) [OpenIFEM_log.txt](https://github.com/OpenIFEM/OpenIFEM/files/11501825/OpenIFEM_log.txt)

metis: 5.1.0
p4est:2.2
petsc:3.15.3
dealii: 9.3.1
gcc: 9.3.0

**Comment by shenchen0414** [comment]
> Many thanks for your prompt responses.
> 
> I have installed deal.II 9.3.1 (which went smoothly as verified in the test shown in the attached "dealii_test_log.txt" ), while keeping all other dependencies without change. I have then tried to install OpenIFEM again and this time it progressed further than the first time but when it reached: [ 29%] Building CXX object source/CMakeFiles/openifem.dir/utilities.cpp.o it then aborted due to fatal errors as shown in the attached "OpenIFEM_log" . There seems to be a lot of petsc mentions in this error, and so I wonder again if this time it has to do with dependencies versions and I need to downgrade petsc? if that is the case, would you please let me know of the dependencies versions you are running OpenIFEM on so I can replicate them, namely: 1- MPI: 2- PETSc: , Mumps: , Hypre: 3- p4est: 4- METIS: 5- deal.II: 9.3.1 Blas: Lapack: Scalapack Umfpack:
> 
> I really appreciate your help.
> 
> [dealii_test_log.txt](https://github.com/OpenIFEM/OpenIFEM/files/11501824/dealii_test_log.txt) [OpenIFEM_log.txt](https://github.com/OpenIFEM/OpenIFEM/files/11501825/OpenIFEM_log.txt)

Please let us know if you still have issues on installation, thanks!

**Comment by shenchen0414** [comment]
> [Failed-Tests-Log.txt](https://github.com/OpenIFEM/OpenIFEM/files/11564049/Failed-Tests-Log.txt) [OpenIFEM_log.txt](https://github.com/OpenIFEM/OpenIFEM/files/11564050/OpenIFEM_log.txt) [OpenIFEM_TEST_Results.txt](https://github.com/OpenIFEM/OpenIFEM/files/11564051/OpenIFEM_TEST_Results.txt)
> 
> Apologies for the late reply, but it took me a long time to try and figure out how to downgrade the dependables to older versions. Nevertheless, once I had them downgraded to the versions you kindly provided, the OpenIFEM installation was successful as shown in the attached OpenIFEM_log file. When I subsequently ran tests 1 to 28, however, some tests – namely tests 6, 7, 8, 9, and 18 – failed as shown in the attached Failed-Tests-Log file. My question is that is the failure of those tests stemming from physical/computational related issues (e.g. due to some parameters values, timestep size, …etc) or is it due to issues with the installation and/or dependencies? Finally, many thanks for your prompt responses and your interest in solving the issue.

Glad it worked out for you! I have looked at the test results for OpenIFEM and they are not errors due to installation. Some of the physical parameters of the tests need to be updated in the future. It looks like you have successfully built your OpenIFEM, please create a new issue when you have other questions using the software. This issue is closed.
